repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: '21.7b0'
  hooks:
    - id: black
      language_version: python3
      exclude: (hello_neopixel/_version|versioneer).py
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ['--config=setup.cfg']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      args: ['--config=setup.cfg']
      follow_imports: "silent"
