# personal development environment for MicroPython based projects on ESP boards
name: espy
dependencies:
  - python=3
  - ipython
  - jupyter
  - pre-commit
  - black
  - isort
  - flake8
  - mypy
  - pytest
  - pytest-cov
  - pip
  - esptool
  - docopt
  # below are needed by ampy
  - click
  - python-dotenv
  - pip:
      - adafruit-ampy>=1.0.5,<1.1
      # TODO: add pytest-subtests once this is resolved:
      # https://github.com/pytest-dev/pytest-subtests/issues/26
